apiVersion: v1
kind: Service
metadata:
  name: ml-model
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4010
  selector:
    app: ml-model
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      imagePullSecrets:
      - name: image-registry-secret
      containers:
        - name: ml-model
          image: dhavalmj007/model-serving:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 4010

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-model
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: ml-model.a355897ccb3d4de3bed2.centralindia.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ml-model
            port:
              number: 80