apiVersion: v1
kind: Service
metadata:
  name: gha-python-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4010
  selector:
    app: gha-python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gha-python-app
  template:
    metadata:
      labels:
        app: gha-python-app
    spec:
      imagePullSecrets:
      - name: image-registry-secret
      containers:
        - name: gha-python-app
          image: dhavalmj007/model-serving:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 4010
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gha-python-app
spec:
  port:
    targetPort: 4010
  to:
    kind: Service
    name: gha-python-app