apiVersion: v1
kind: Service
metadata:
  name: ml-model
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4010
  selector:
    app: ml-model
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      imagePullSecrets:
      - name: image-registry-secret
      containers:
        - name: ml-model
          image: modelserve:v1
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "3000m"
          ports:
            - containerPort: 4010