BASE_ROUTE = '/model'
DOCS_ROUTE = f'{BASE_ROUTE}/docs'
HEALTHCHECK_ROUTE = f'{BASE_ROUTE}/healthcheck'

PREDICTION_ROUTE = f'/predict'
PREDICTION_FILE_ROUTE = f'/predict_on_file'

ROUTE_NOT_LOGGED = [HEALTHCHECK_ROUTE]