name: ci

on:
  push:
    branches:
      - 'model'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          path: /root/.cache/pip
          key: pip-{{ hashFiles('requirements*.txt') }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dhavalmj007/model-serving:latest
  openshift:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: model # branch
      -
        name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      -
        name: Deploy to openshift
        run: oc apply -f deploy-to-openshift.yaml